### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by fulldecent** [vincentsaluzzo/Homebrew-GUI#2]
Please make a note of project status in the README.md. 

What are the minimal feature set we should be working on to achieve a 1.0 release?

**Comment by vincentsaluzzo** [comment]
Hi @fulldecent ,

I need to review code and application to determine a real ROADMAP.
I don't realy open Homebrew-GUI Xcode project for several years.
Your work and pull request remind me that's a good idea and a good project.

I come back to you later for given a roadmap ;)

**Comment by fulldecent** [comment]
Closing, Cakebrew is actively maintained
